# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      PORT: 3001
      SUPABASE_URL: 'https://lnittdgflsxwbofnrpul.supabase.co'
      SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuaXR0ZGdmbHN4d2JvZm5ycHVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzUwOTQ5NzMsImV4cCI6MTk5MDY3MDk3M30.3XFoAVUDDzaoDq7AqkZ3D1lGcnTsIOpzuPQ8fk0J6w0'
      JWTSECRET: 'aQ/qA4Pe4uOK+RMyGdm++AAlYa6lTVbDZrpiWMqXPmKVm0lyT9VNmhFuRFE25m9fMFxm/QCXaoPvBckfzbOH8Q=='
      X_APP_ID: 8aca1c28
      X_APP_KEY: f7e659dbd852ad404c17ed83178fd6ec
      EXERCISE_API_KEY: "GrNd+jYhbHAK56nGd/uX7A==t64Gn5TjsODSYjp0"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Node.js and NPM
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
      working-directory: ./Server
    - name: Run tests
      run: npm test
      working-directory: ./Server

